from functions.get_files_info import get_files_info

print("Expecting:") 
print("Result for current directory:")
print("- main.py: file_size=576 bytes, is_dir=False")
print("- tests.py: file_size=1343 bytes, is_dir=False")
print("- pkg: file_size=92 bytes, is_dir=True")
print("- lorem.txt: file_size=28 bytes, is_dir=False")
print("=====================================================")
print("Actual:")
print("Result for current directory:")
print(get_files_info("calculator", "."))
print("=====================================================")

print("Expecting:") 
print("Result for 'pkg' directory:")
print("- calculator.py: file_size=576 bytes, is_dir=False")
print("- render.py: file_size=1343 bytes, is_dir=False")
print("- __pycache__: file_size=92 bytes, is_dir=True")
print("- morelorem.txt: file_size=28 bytes, is_dir=False")
print("=====================================================")
print("Actual:")
print("Result for 'pkg' directory:")
print(get_files_info("calculator", "pkg"))
print("=====================================================")

print("Expecting:") 
print("Result for '/bin' directory:")
print("Error: Cannot list '/bin' as it is outside the permitted working directory")
print("=====================================================")
print("Actual:")
print(get_files_info("calculator", "/bin"))
print("=====================================================")

print("Expecting:") 
print("Result for '../' directory:")
print("Error: Cannot list '../' as it is outside the permitted working directory")
print("=====================================================")
print("Actual:")
print(get_files_info("calculator", "/.."))
print("=====================================================")
